#!/usr/bin/env perl

use strict;
use warnings;
use 5.012;
use autodie;

# core modules
use Cwd qw/abs_path/;
use File::Basename qw/basename/;
use File::Copy qw/move/;
use File::Fetch;
use File::Find;
use File::Temp;
use Getopt::Long;
use IO::Compress::Gzip qw/$GzipError/;
use IPC::Cmd qw/can_run run/;
use JSON::PP qw/decode_json/;
use Pod::Usage;

our $VERSION = 0.002;
use constant PROGRAM => 'dl_blast';

my $db;
my $base_url = 'https://ftp.ncbi.nih.gov/blast/db';
my $dir_blast;
my $fo_fasta; 
my $fo_taxmap;
my $quiet = 0;
my $gzip = 0;
my $tmpdir;
my $overwrite = 0;

GetOptions(
    'db=s' => \$db,
    'base_url=s' => \$base_url,
    'dir_out=s' => \$dir_blast,
    'fasta=s' => \$fo_fasta,
    'tax_map=s' => \$fo_taxmap,
    'tmpdir=s' => \$tmpdir,
    'gzip' => \$gzip,
    'quiet' => \$quiet,
    'overwrite' => \$overwrite,
    'help' => sub{ pod2usage(-verbose => 2, -exitval => 0); },
    'version' => sub{ say 'This is ',PROGRAM,' v', $VERSION; exit },
);

use constant ERROR => 'ERROR';
use constant WARNING => 'WARNING';
use constant INFO => 'INFO';

my $TAR = can_run('tar')
    // plog( ERROR, 'setup', "'tar' is required but not found\n" );
my $BLASTDBCMD = can_run('blastdbcmd');
if (! defined $BLASTDBCMD && (defined $fo_fasta || defined $fo_taxmap)) {
    plog(
        ERROR,
        'setup',
        "'blastdbcmd' is required for conversion but not found"
        . " (likely BLAST is not installed)"
    );
}
plog(ERROR, 'setup', "Must specify BLAST database (--db)")
    if (! defined $db);

$fo_fasta = abs_path($fo_fasta)
    if (defined $fo_fasta);
$dir_blast = abs_path($dir_blast)
    if (defined $dir_blast);
$fo_taxmap = abs_path($fo_taxmap)
    if (defined $fo_taxmap);

$tmpdir //= $ENV{TMPDIR} // '/tmp';

# download database metadata
my $meta = fetch_meta($db);
plog( ERROR, 'setup', "DB name mismatch in fetched metadata\n" )
    if ($db ne $meta->{dbname});

# check if file and/or status flag already exist, and if so bail out
if (defined $fo_fasta && -e $fo_fasta && ! defined $dir_blast) {
    if (-e "$fo_fasta.ok") {
        plog( INFO, 'output', "File $fo_fasta.ok exists, nothing more to do" );
        exit;
    }
    elsif (! $overwrite) {
        plog( ERROR, 'output', "File $fo_fasta exists and --overwrite"
            . " not given, aborting" );
    }
}

# download database files
my $staging = File::Temp->newdir(DIR => $tmpdir);
my $n_files = scalar @{ $meta->{files} };
my $n_downloaded = 0;
for my $fn (@{ $meta->{files} }) {
    ++$n_downloaded;
    plog( INFO, 'download', "Downloading $n_downloaded/$n_files: $fn" );
    download($fn, $staging);
}

# get total size of downloaded database files
my $fetched_size = 0;
find( {wanted => \&count_size, no_chdir => 1}, $staging );

# convert to FASTA if requested
if (defined $fo_fasta) {
    plog( INFO, 'output', "Writing FASTA to $fo_fasta" );
    my $n_seqs = write_fasta("$staging/$db", $fo_fasta);
    if ($n_seqs != $meta->{'number-of-sequences'}) {
        plog( ERROR, 'output', sprintf(
            "Conversion to FASTA returned wrong sequence count"
            . " (expected %s, got %s)\n",
            $meta->{'number-of-sequences'},
            $n_seqs,
        ));
    }
    # create a '*.ok' file as a flag to indicate a complete download
    open my $out, '>', "$fo_fasta.ok";
    close $out;
}

# convert to taxonomy map if requested
if (defined $fo_taxmap) {
    plog( INFO, 'output', "Writing tax map to $fo_taxmap" );
    my $n_seqs = write_taxmap("$staging/$db", $fo_taxmap);
    # tax map count can be (and often is) greater than the sequence count
    # because of exact duplicate sequences with multiple IDs. Just check
    # that we have *at least* as many entries as sequences
    if ($n_seqs < $meta->{'number-of-sequences'}) {
        plog( ERROR, 'output', sprintf(
            "Conversion to tax map returned too few mappings"
            . " (expected %s, got %s)\n",
            $meta->{'number-of-sequences'},
            $n_seqs,
        ));
    }
}

# copy BLAST database files to final location if requested
if (defined $dir_blast) {
    find({wanted => \&final_move, no_chdir => 1}, $staging);
    # recalculate total size of downloaded database files to check for partial
    # copies (e.g. disk out-of-space conditions, etc)
    $fetched_size = 0;
    find({wanted => \&count_size, no_chdir => 1}, $dir_blast);
    plog( ERROR, 'output', sprintf(
        "Size mismatch of final database: expected %s, got %s\n",
        $meta->{bytes_total},
        $fetched_size,
    )) if ($meta->{bytes_total} != $fetched_size);
}

exit;

sub write_fasta {

    my ($db, $fn_out) = @_;

    my @cmd = (
        $BLASTDBCMD,
        '-db' => "$db",
        '-entry' => 'all',
        '-outfmt' =>  '%f',
    );

    my $out;
    if ($gzip) {
        $fn_out .= '.gz' if ($fn_out !~ /\.gz$/);
        $out = IO::Compress::Gzip->new("$fn_out")
            or plog( ERROR, 'output',
                "Failed to open $fn_out for writing: $GzipError" );
    }
    else {
        open $out, '>', $fn_out;
    }

    open my $stream, '-|', @cmd;
    my $n_seqs = 0;
    while (my $line = <$stream>) {
        ++$n_seqs if ($line =~ /^>/);
        print {$out} $line;
    }
    close $out;
    close $stream
        or plog( ERROR, 'output', "Error writing FASTA: $@\n");
    return $n_seqs;

}

sub write_taxmap {

    my ($db, $fn_out) = @_;

    my @cmd = (
        $BLASTDBCMD,
        '-db' => "$db",
        '-entry' => 'all',
        '-outfmt' =>  '%a %T %t',
    );
    my $n_seqs = 0;
    my $out;
    if ($gzip) {
        $fn_out .= '.gz' if ($fn_out !~ /\.gz$/);
        $out = IO::Compress::Gzip->new("$fn_out")
            or plog( ERROR, 'output',
                "Failed to open $fn_out for writing: $GzipError" );
    }
    else {
        open $out, '>', $fn_out;
    }
    open my $stream, '-|', @cmd;
    while (my $line = <$stream>) {
        my @f = split ' ', $line;
        say {$out} join "\t",
            (shift @f),
            (shift @f),
            join(' ', @f),
        ;
        ++$n_seqs;
    }
    close $out;
    close $stream
        or plog( ERROR, 'output', "Error writing tax map: $@\n" );
    return $n_seqs;

}

sub count_size {

    return if (! -f $_);
    return if (basename($_) !~ /^$db\./);
    $fetched_size += -s $_;

}

sub final_move {

    return if (! -f $_);
    move $_, $dir_blast
        or plog( ERROR, 'output', "Error moving $_: $@" );

}

sub download {
    
    my ($fn_in, $dir_out) = @_;

    # rsync is typically faster if present on the system
    $fn_in =~ s/^ftp/rsync/
        if can_run('rsync');

    my $fn_out = join '/', $dir_out, basename($fn_in);
    my $ua = File::Fetch->new(uri => $fn_in);
    my $ret;
    for (0..2) {
        $ret = $ua->fetch(to => $dir_out);
        if (! $ret) {
            unlink $fn_out if (-e $fn_out);
            next;
        }
    }
    plog( ERROR, 'download',
        sprintf("Failed to download %s: %s\n", $fn_in, $ua->error)
    ) if (! $ret);
    my @cmd = (
        $TAR,
        '-C' => $dir_out,
        '-xf' => $fn_out,
    );
    my ($ok, $err) = run(command => \@cmd);
    plog( ERROR, 'download', "Failed to decompress $fn_out: $err\n" )
        if (! $ok);
    unlink $fn_out;

}

sub fetch_meta {

    my ($db) = @_;

    plog( INFO, 'setup', "Fetching metadata for database: $db" );
    my $fn = "$db-nucl-metadata.json";
    my $scratch = File::Temp->newdir(DIR => $tmpdir);
    my $ua = File::Fetch->new(uri => "$base_url/$fn");
    my $where = $ua->fetch(to => $scratch)
        or plog(
            ERROR,
            'setup',
            "Error downloading metadata for $db: is this a valid database?"
        );
    local $/ = undef;
    open my $in, '<', $where;
    my $data = <$in>;
    close $in;
    my $meta = decode_json($data)
        or plog( ERROR, 'setup', "Failed to parse metadata file: $@" );

    return $meta;

}

sub plog {

    my ($lvl, $unit, $msg) = @_;
    if ($lvl ne ERROR) {
        say STDERR "[dl_blast::$unit] $lvl $msg"
            if (! $quiet);
    }
    else {
        die "[dl_blast::$unit] $lvl $msg\n";
    }

}

__END__

=head1 NAME

dl_blast - Download an NCBI BLAST database and optionally convert to FASTA

=head1 SYNOPSIS

dl_blast --db nt [ @other options ]

=head1 DESCRIPTION

This utility downloads and decompresses an NCBI BLAST database by name. It can
also optionally convert and output the database as FASTA and/or a taxonomic
mapping file. It is intentionally designed to be simple -- it doesn't, for
instance, do full hash-based integrity checks on downloaded files or resume
from partial downloads (there are other tools available for this). It does do
a rudimentary check of exact byte size of all downloaded files compared to the
advertised byte size in the database metadata. It makes use of only core Perl
modules and thus can easily be included as a utility in other software packages.

=head1 PREREQUISITES

The following external tools must be available in the system path:

=over 4

=item B<tar> (preferably GNU tar or another flavor capable of gzip decompression)

=item B<blastdbcmd> (part of the NCBI BLAST suite; only necessary for
FASTA/taxonomy conversion)

=back

=head1 OPTIONS

=head2 Input

=over 4

=item B<--db> I<string>

Name of BLAST database to download (case-sensitive); required

=item B<--base_url> I<string>

Base URL to download from, if using mirror (default:
'https://ftp.ncbi.nih.gov/blast/db')

=back

=head2 Output 

=over 4

=item B<--dir_out> I<path>

Directory in which to save BLAST database files (default: none)

=item B<--fasta> I<filename>

Path at which to save converted FASTA file (default: none)

=item B<--taxmap> I<filename>

Path at which to save tab-delimited accession/taxonomy mapping (default:
none)

=back

=head2 Configuration 

=over 4

=item B<--tmpdir> I<path>

Directory to use as TMP space instead of the system default. Note that
uncompressed downloads can be terabytes in size and are always saved to a
temporary scratch space first. (default: $TMPDIR or /tmp)

=item B<--gzip>

Compress output FASTA or taxonomy mapping with gzip (no effect on BLAST
database files) (default: off)

=item B<--quiet>

If set, don't write status messages to STDERR (default: off)

=item B<--overwrite>

If set, silently overwrite any existing files at the specified output paths.
If not set and file(s) exist, nothing is written and the program either exits
normally (if a "*.ok" file is also found) or throws and error. Note that this
currently has no effect on the BLAST database file downloads, only on FASTA
and taxonomy map output. (default: off)

=item B<--help>

Print usage description and exit

=item B<--version>

Print software version and exit

=back

=head1 CAVEATS AND BUGS

Please submit bug reports to the issue tracker in the distribution repository.

=head1 AUTHOR

Jeremy Volkening (jeremy.volkening@base2bio.com)

=head1 COPYRIGHT AND LICENSE

Copyright 2025 Jeremy Volkening

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program.  If not, see <http://www.gnu.org/licenses/>.

=cut
